/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sdfs.h"

READ_RSP_T *
rpc_read_0x0001_svc(READ_REQ_T *argp, struct svc_req *rqstp)
{
	static READ_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

WRITE_RSP_T *
rpc_write_0x0001_svc(WRITE_REQ_T *argp, struct svc_req *rqstp)
{
	static WRITE_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_open_0x0001_svc(OPEN_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_create_0x0001_svc(CREATE_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

GETATTR_RSP_T *
rpc_getattr_0x0001_svc(GETATTR_REQ_T *argp, struct svc_req *rqstp)
{
	static GETATTR_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

READDIR_RSP_T *
rpc_readdir_0x0001_svc(READDIR_REQ_T *argp, struct svc_req *rqstp)
{
	static READDIR_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_access_0x0001_svc(ACCESS_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_mknod_0x0001_svc(MKNOD_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_mkdir_0x0001_svc(MKDIR_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_unlink_0x0001_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_rmdir_0x0001_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_symlink_0x0001_svc(SYMLINK_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_rename_0x0001_svc(RENAME_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_link_0x0001_svc(LINK_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_chmod_0x0001_svc(CHMOD_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_chown_0x0001_svc(CHOWN_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_truncate_0x0001_svc(TRUNCATE_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

READLINK_RSP_T *
rpc_readlink_0x0001_svc(READLINK_REQ_T *argp, struct svc_req *rqstp)
{
	static READLINK_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

STATVFS_RSP_T *
rpc_statvfs_0x0001_svc(char **argp, struct svc_req *rqstp)
{
	static STATVFS_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_setxattr_0x0001_svc(SETXATTR_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

GETXATTR_RSP_T *
rpc_getxattr_0x0001_svc(GETXATTR_REQ_T *argp, struct svc_req *rqstp)
{
	static GETXATTR_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

LISTXATTR_RSP_T *
rpc_listxattr_0x0001_svc(LISTXATTR_REQ_T *argp, struct svc_req *rqstp)
{
	static LISTXATTR_RSP_T  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_removexattr_0x0001_svc(REMOVEXATTR_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rpc_fallocate_0x0001_svc(FALLOCATE_REQ_T *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
